INFO - 2023-09-17 10:26:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-17 10:26:58 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost:3307', 'root', '', 'app', 3307, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\app\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\app\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(919): App\Controllers\Home->index()
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\app\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\app\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\app\app\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\app\app\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(919): App\Controllers\Home->index()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\app\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-09-17 10:26:58 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `data`
WHERE `status` = :status:
ORDER BY `id`', [...], false)
 3 APPPATH\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\app\\public\\index.php')
INFO - 2023-09-17 10:27:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-17 10:27:44 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'app', 3307, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\app\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\app\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(919): App\Controllers\Home->index()
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\app\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\app\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\app\app\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\app\app\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(919): App\Controllers\Home->index()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\app\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-09-17 10:27:44 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `data`
WHERE `status` = :status:
ORDER BY `id`', [...], false)
 3 APPPATH\Models\CrudModel.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(9): App\Models\CrudModel->getAll('data', 'id')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\app\\public\\index.php')
INFO - 2023-09-17 10:28:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
